baseURL = "https://www.ykiko.me"
theme = "PaperMod"

defaultContentLanguage = "zh-cn"
defaultContentLanguageInSubdir = true

enableRobotsTXT = true
summaryLength = 30
hasCJKLanguage = true
enableEmoji = true

buildDrafts = false
buildFuture = false

[pagination]
pagerSize = 100

[services.googleAnalytics]
ID = "G-PEDMYR1V0K"

[imaging]
anchor = "Center"

[frontmatter]
lastmod = ["lastmod", "modified", "updated", "date", "publishDate"]

[taxonomies]
tag = "tags"
category = "categories"
author = "authors"
series = "series"

[sitemap]
changefreq = "always"
filename = "sitemap.xml"
priority = 0.5

[outputs]
home = ["HTML", "RSS", "JSON"]

[languages.en]
contentDir = "content/en"

[languages.zh-cn]
contentDir = "content/zh-cn"
