mainSections = ["articles"]

defaultTheme = "auto"
disableThemeToggle = false
disableSpecial1stPost = true
disableScrollToTop = false
displayFullLangName = true

ShowReadingTime = true
ShowWordCount = true
ShowShareButtons = false
ShowPostNavLinks = true
ShowBreadCrumbs = false
ShowCodeCopyButtons = true
ShowRssButtonInSectionTermList = true
ShowAllPagesInArchive = true
ShowPageNums = true
ShowToc = true

comments = true
hideFooter = true
DateFormat = "2006-01-02"

[assets]
favicon = "favicon.ico"

[label]
text = "ykiko's blog"

[footer]
hideCopyright = true

[[socialIcons]]
name = "github"
url = "https://github.com/16bit-ykiko"

[[socialIcons]]
name = "email"
url = "mailto:ykiko@clice.io"

[[socialIcons]]
name = "zhihu"
url = "https://www.zhihu.com/people/16bit-ykiko"

[[socialIcons]]
name = "bilibili"
url = "https://space.bilibili.com/360835081"
