name: Ultimate Manual Debug Session

on:
  pull_request:
    branches: [main]

jobs:
  vm:
    runs-on: [macos-latest]

    steps:
      - uses: actions/checkout@v4

      - name: set up
        uses: fawazahmed0/action-debug-vscode@main
