name: Pages

on:
  schedule:
    - cron: "0 0 * * *"

  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install beautifulsoup4 requests

      - name: Update pages
        env:
          COOKIE_TEXT: ${{ secrets.COOKIE_TEXT }}
        run: |
          python scripts/update.py

      - name: Commit changes
        run: |
          git config --global user.name "ykiko"
          git config --global user.email "ykikoykikoykiko@gmail.com"
          git add .
          git commit -m "Update articles automatically"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "latest"

      - name: Build
        run: | 
          cd website
          mkdir themes
          cd themes
          git clone https://github.com/jpanther/congo -b stable --depth=1
          ls
          cd ..
          hugo

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: website/public
