name: Pages

on:
  schedule:
    - cron: "0 0 * * *"

  push:
    branches:
      - main

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install beautifulsoup4 requests

      - name: Update pages
        run: python script/update.py

      - name: Setup Git
        run: |
          git config --global user.name "ykiko"
          git config --global user.email "ykikoykikoykiko@gmail.com"

      - name: Add changes
        run: git add .

      - name: Commit changes
        run: git commit -m "Update articles automatically"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

  deploy:
    runs-on: ubuntu-latest

    needs: update

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js 20
        uses: actions/setup-node@v1
        with:
          node-version: "20"

      - name: Cache NPM dependencies
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.OS }}-npm-cache
          restore-keys: |
            ${{ runner.OS }}-npm-cache

      - name: Install Dependencies
        run: cd hexo && npm install && git clone -b master https://github.com/jerryc127/hexo-theme-butterfly.git themes/butterfly

      - name: Build
        run: cd hexo && npm run clean && npm run build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: hexo/public
